### ISSUE TITLE
Packages not visible for Limited Access - Free due to User field

### ISSUE THREAD

**Issue by mmablom** [ronitnuguru/Package-Visualizer#1]
I've been trying to give our developers, who use separate Limited Access Users, to access the Package Visualizer. After following the configuration guide, the page kept not showing the list of packages, which does show for an Admin. After looking through the code I noticed that the Tooling API was used to load the packages and tried the request through my LA User. This produced the error "No such column 'Id' on entity 'User'". This seems to be due to the `CreatedBy.Name` field, because when changing it to `CreatedById` the query is run successfully. See the examples below.

As far as I can see, there's no way to give a Limited Access User object access to the User through the Tooling API. Could a fallback be added in the package in case the User object is not accessible?

**Failed request**

Query:
```sql
SELECT Id, 
  ContainerOptions, 
  Description, 
  Name, 
  NamespacePrefix, 
  SubscriberPackageID, 
  isOrgDependent, 
  PackageErrorUsername, 
  WasTransferred, 
  CreatedBy.Name, 
  CreatedDate 
FROM Package2 
WHERE IsDeprecated = false 
ORDER BY Name ASC 
LIMIT 500
```

Response:
```json
[
    {
        "message": "No such column 'Id' on entity 'User'. If you are attempting to use a custom field, be sure to append the '__c' after the custom field name. Please reference your WSDL or the describe call for the appropriate names.",
        "errorCode": "INVALID_FIELD"
    }
]
```

**Successful Request**

Query:
```sql
SELECT Id, 
  ContainerOptions, 
  Description, 
  Name, 
  NamespacePrefix, 
  SubscriberPackageID, 
  isOrgDependent, 
  PackageErrorUsername, 
  WasTransferred, 
  CreatedById, 
  CreatedDate 
FROM Package2
WHERE IsDeprecated = false 
ORDER BY Name ASC 
LIMIT 500
```

Response:
```json
{
    "size": 26,
    "totalSize": 26,
    "done": true,
    "queryLocator": null,
    "entityTypeName": "Package2",
    "records": [...]
}
```

**Comment by ronitnuguru** [comment]
@mmablom The Limited Access User Profile comes as a part of [DX Tooling](https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/dev_hub_license.htm) for [users](https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_setup_add_free_license_users.htm) who need access to Dev Hub for package creation, scratch orgs via the CLI. These users don't need access to standard or custom objects and Platform's custom applications on Salesforce

Unfortunately, since Package Visualizer acts as UI and is a custom application on Salesforce, you'll need a Salesforce license and a stronger profile to leverage for your users. Only other alternative here is to give your users the appropriate [permission sets](https://developer.salesforce.com/docs/atlas.en-us.248.0.sfdx_dev.meta/sfdx_dev/sfdx_setup_permission_set.htm) and [system permissions](https://developer.salesforce.com/docs/atlas.en-us.pkg2_dev.meta/pkg2_dev/sfdx_pkg_user_permission.htm) so that they can view the package details and versions via the CLI

**Comment by mmablom** [comment]
@ronitnuguru Ah, thanks for the clarification and quick response. We also have Salesforce Platform licenses, which are used for project management and other internal administration. Initially I tried to give these Users access, but the license doesn't allow packaging permissions. I get the same error via the tooling API when trying as the Platform user, unless I provide 'View Setup and Configuration' permission. However, the Subscribers and other information is not working in that case. Should the Visualizer be usable for a Platform User or is this license also inadequate?

**Comment by mmablom** [comment]
@ronitnuguru I've compared our custom Profile, and it turns out that 'View Setup and Configuration' is enabled by default in the Standard Platform User Profile, but is not enabled for our custom Profile. I'll discuss if that's an option for us so we can at least access the packages.

Unfortunately the subscribers will not be easily accessible then, as we won't be using the System Admin due to the other data contained in the org.
